name: Build and Push docker images

on:
  push:
    branches: [ "main" ]

jobs:

  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Shorten SHA
        id: shorten_sha
        run: echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: vidraxmax/frontend:latest, vidraxmax/frontend:${{ steps.shorten_sha.outputs.short_sha }}-${{ github.run_number }}

  build-be:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Shorten SHA
        id: shorten_sha
        run: echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: vidraxmax/backend:latest, vidraxmax/backend:${{ steps.shorten_sha.outputs.short_sha }}-${{ github.run_number }}
